name: animal_search
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  google_maps_flutter: ^2.2.8
  image_picker: ^0.8.4+4
  flutter_svg: ^1.1.6
  firebase_core: ^2.24.2
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.13.5
  firebase_storage: ^11.5.5
  firebase_app_check: ^0.2.2
  permission_handler: ^11.0.1
  path: ^1.9.0
  http: ^0.13.5
  cached_network_image: ^3.2.3
  share_plus: ^7.0.2
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1  

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/AnimalSearch.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/animal.svg
    - assets/icons/plus.svg
    - assets/icons/AnimalSearch.png
    - assets/icons/google.png
