// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBlt5Es7IpxsnJzcIQoOBP8iM1vg2JESA',
    appId: '1:827444107597:web:c32795f20a20636a243f04',
    messagingSenderId: '827444107597',
    projectId: 'animalsearch-d7828',
    authDomain: 'animalsearch-d7828.firebaseapp.com',
    storageBucket: 'animalsearch-d7828.firebasestorage.app',
    measurementId: 'G-SPJ3SBM8CM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe-WGTNG1yscjKFPzVaINpBDKhEj75i9Y',
    appId: '1:827444107597:android:6b9adcc37b0cd5c9243f04',
    messagingSenderId: '827444107597',
    projectId: 'animalsearch-d7828',
    storageBucket: 'animalsearch-d7828.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdt_o98UVeTt-4M73oCA6J9KECmn1zAGo',
    appId: '1:827444107597:ios:36bde1b45a00187f243f04',
    messagingSenderId: '827444107597',
    projectId: 'animalsearch-d7828',
    storageBucket: 'animalsearch-d7828.firebasestorage.app',
    iosBundleId: 'com.example.animalSearchFront',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdt_o98UVeTt-4M73oCA6J9KECmn1zAGo',
    appId: '1:827444107597:ios:36bde1b45a00187f243f04',
    messagingSenderId: '827444107597',
    projectId: 'animalsearch-d7828',
    storageBucket: 'animalsearch-d7828.firebasestorage.app',
    iosBundleId: 'com.example.animalSearchFront',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBlt5Es7IpxsnJzcIQoOBP8iM1vg2JESA',
    appId: '1:827444107597:web:841c1da29f5f51ae243f04',
    messagingSenderId: '827444107597',
    projectId: 'animalsearch-d7828',
    authDomain: 'animalsearch-d7828.firebaseapp.com',
    storageBucket: 'animalsearch-d7828.firebasestorage.app',
    measurementId: 'G-4XF5P1M77F',
  );

}